### ISSUE TITLE
All the boxes are empty and didn't give any rewards.

### ISSUE THREAD

**Issue by 1825679767** [AnchyDev/LadyLuck#1]
All the boxes are empty and didn't give any rewards.

**Comment by AnchyDev** [comment]
This module is pretty much abandoned. I will update the README.

**Comment by 1825679767** [comment]
This is a very good module, please don't give up, please

**Comment by AnchyDev** [comment]
> This is a very good module, please don't give up, please

I have cleaned up some of the code of the module and it should be simpler to use.
Let me know if that fixes any problems.
