### ISSUE TITLE
If you log out in the lottery room, Lady Luck cannot teleport you out

### ISSUE THREAD

**Issue by Auz-kiee** [AnchyDev/LadyLuck#2]
If you log out in the lottery room, logging back in and trying to exit with Lady Luck wont work, she cannot teleport you out.
This may be due to the temporary variable of your location xyz being lost on logout.

I will try to think of a fix but just logging it in case you see it first.

**Comment by AnchyDev** [comment]
I might just return the player when they logout.

**Comment by AnchyDev** [comment]
This should hopefully be fixed by b5e60f4
